version: '3'

services:
  server:
    build: server
    command: ./gradlew bootrun
    restart: always
    volumes:
      - ./server:/code
    ports:
      - "8080:8080"

  web:
    build: web
    ports:
      - "80:80"
